=== 6RiverSystems/6dk/app/schemas/profile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "friendly_name": {
      "type": "string"
    },
    "active": {
      "type": "boolean"
    },
    "northbound_messages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        },
        {
          "type": "object",
          "properties": {
            "send": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "wms_host": {
              "type": "string"
            },
            "wms_path": {
              "type": "string"
            },
            "wms_port": {
              "type": "integer"
            },
            "wms_headers": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "send",
            "name",
            "wms_host",
            "wms_path",
            "wms_port",
            "wms_headers"
          ]
        }
      ]
    },
    "southbound_messages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "exception_pick": {
              "type": "boolean"
            },
            "sanitizers": {
              "type": "object",
              "properties": {
                "containerType": {
                  "type": "boolean"
                },
                "sourceLocation": {
                  "type": "boolean"
                }
              },
              "required": [
                "containerType",
                "sourceLocation"
              ]
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "exception_pick",
            "sanitizers",
            "name"
          ]
        },
        {
          "type": "object",
          "properties": {
            "exception_pick": {
              "type": "boolean"
            },
            "sanitizers": {
              "type": "object",
              "properties": {
                "containerType": {
                  "type": "boolean"
                },
                "sourceLocation": {
                  "type": "boolean"
                }
              },
              "required": [
                "containerType",
                "sourceLocation"
              ]
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "exception_pick",
            "sanitizers",
            "name"
          ]
        },
        {
          "type": "object",
          "properties": {
            "exception_pick": {
              "type": "boolean"
            },
            "sanitizers": {
              "type": "object",
              "properties": {
                "containerType": {
                  "type": "boolean"
                },
                "sourceLocation": {
                  "type": "boolean"
                }
              },
              "required": [
                "containerType",
                "sourceLocation"
              ]
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "exception_pick",
            "sanitizers",
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "friendly_name",
    "active",
    "northbound_messages",
    "southbound_messages"
  ]
}

=== 6RiverSystems/6dk/app/templates/json/standard_profile.json
{
  "friendly_name": "6dk-profile",
  "active": false,
  "northbound_messages": [
    {
      "send": false,
      "name": "acknowledgement",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "container-accepted",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "container-validation",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "print-request",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "container-inducted",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "pick-task-picked",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "container-picked-complete",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    },
    {
      "send": false,
      "name": "container-taken-off",
      "wms_host": null,
      "wms_path": null,
      "wms_port": 443,
      "wms_headers": []
    }
  ],
  "southbound_messages": [
    {
      "exception_pick": false,
      "sanitizers": {
        "containerType": true,
        "sourceLocation": true
      },
      "name": "pick-waves"
    },
    {
      "exception_pick": false,
      "sanitizers": {
        "containerType": true,
        "sourceLocation": true
      },
      "name": "group-updates"
    },
    {
      "exception_pick": false,
      "sanitizers": {
        "containerType": true,
        "sourceLocation": true
      },
      "name": "group-cancels"
    }
  ]
}
